### ISSUE TITLE
Required libraries

### ISSUE THREAD

**Issue by smlatorreo** [thackl/kmer-scripts#3]
Hello.
Thanks for sharing this tool. However, it would be nice if you can point the required .pm libraries for the using of the programs. I realized that some of them are in https://github.com/BioInf-Wuerzburg

However, I'm not sure whether the Jellyfish.pm library is the same Perl wrapper one can find after compiling jellyfish.
Thanks!

**Comment by thackl** [comment]
Hi,

if you are only interested in using `kmer-plot`, you don't need any Perl libraries. The script is just a bash wrapper around an R code back-end.

In case you want to use the other scripts, the following libraries should be what you need:

```
# helper functions
git clone https://github.com/thackl/perl5lib-Handy.git
git clone https://github.com/BioInf-Wuerzburg/perl5lib-Verbose.git

# handling kmers
git clone https://github.com/thackl/perl5lib-Kmer.git
git clone https://github.com/thackl/perl5lib-Jellyfish.git

# reading sequences
git clone https://github.com/BioInf-Wuerzburg/perl5lib-Fasta.git
git clone https://github.com/BioInf-Wuerzburg/perl5lib-Fastq.git
```

Sorry for not having this repository documented better, but I didn't really plan on this being a ready to use package, but rather just a repo for me. Let me know if you have any further questions.
